version: 2
updates:
- package-ecosystem: npm
  directories:
    - "/"
    - "/benchmarks/*"
    - "/docs/*"
    - "/examples/*"
    - "/interop/*"
    - "/packages/*"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 20
  commit-message:
    prefix: "deps"
    prefix-development: "chore"
  groups:
    interplanetary-deps: # group all deps that should be updated when Helia deps need updated
      patterns:
        - "*helia*"
        - "*libp2p*"
        - "*multiformats*"
        - "*blockstore*"
        - "*datastore*"
        - "*kubo*"
        - "ipfsd-ctl"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: chore
