volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  front-tier:
  back-tier:

services:
  bootstrapper:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8888:8888
      - 8899:8899
      - 4101:4101
      - 4102:4102
      - 4001:4001
      - 4003:4003
    environment:
      - CONFIG_FLAGS=""
    volumes:
      - ./config.json:/config.json
      - ./snapshot-dir:/app/snapshot-dir
    command: node dist/src/index.js --config config.json --enable-kademlia --enable-autonat
    network_mode: host

  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    pull_policy: if_not_present
    profiles: ['dashboard'] # only runs with dashboard profile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9080:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    pull_policy: if_not_present
    profiles: ['dashboard'] # only runs with dashboard profile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9181:3000
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards
      # - ./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      # - ./config/grafana:/var/lib/grafana
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - back-tier
      - front-tier

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    profiles: ['linux'] # only runs with linux profile
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    profiles: ['linux'] # only runs with linux profile
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global
