{
 "title": "js-libp2p bootstrapper default dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "heatmap_buckets", "query": "${VAR_HEATMAP_BUCKETS}" },
   { "name": "axisWidth", "query": "${VAR_AXISWIDTH}" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"js-libp2p\", instance=\"libp2p-bootstrap-js\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connection Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "libp2p_connection_manager_connections{}",
     "legendFormat": "{{libp2p_connection_manager_connections}}"
    }
   ]
  },
  {
   "title": "Connections by transport",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "libp2p_connection_transports_total",
     "legendFormat": "{{libp2p_connection_transports_total}}"
    }
   ]
  },
  {
   "title": "Dial queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "libp2p_dial_queue", "legendFormat": "{{libp2p_dial_queue}}" }
   ]
  },
  {
   "title": "Dial results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(libp2p_connection_manager_dials_total[$__rate_interval])",
     "legendFormat": "{{libp2p_connection_manager_dials_total}}"
    },
    {
     "expr": "rate(libp2p_connection_manager_dial_errors_total[$__rate_interval])",
     "legendFormat": "{{libp2p_connection_manager_dial_errors_total}} (error)"
    }
   ]
  },
  {
   "title": "Peer agents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "libp2p_peer_agents_total", "legendFormat": "{{libp2p_peer_agents_total}}" }
   ]
  },
  { "title": "Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "libp2p_protocol_streams_total{}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Bytes received by protocol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "rate(libp2p_data_transfer_bytes_total{protocol!~\"global received\", protocol=~\".* received\"}[$__interval])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Bytes sent by protocol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\n    rate(libp2p_data_transfer_bytes_total{protocol!~\"global sent\", protocol=~\".* sent\"}[$__interval]),\n    \"protocol\",\n    \"$1\",\n    \"protocol\",\n    \"(.*) sent\"\n)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  { "title": "WebSockets Transport", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Listener events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(libp2p_websockets_listener_events_total[$__rate_interval])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Dialer events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "rate(libp2p_websockets_dialer_events_total[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "TCP Transport", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Listener events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(libp2p_tcp_listener_events_total[$__rate_interval])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Dialer events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "rate(libp2p_tcp_dialer_events_total[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Kad-DHT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Running queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    { "expr": "libp2p_kad_dht_running_queries", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Query seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "libp2p_kad_dht_query_time_seconds",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Ping queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    { "expr": "libp2p_kad_dht_ping_queue", "legendFormat": "{{libp2p_kad_dht_ping_queue}}" }
   ]
  },
  {
   "title": "Inbound RPC requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "rate(libp2p_kad_dht_inbound_rpc_requests_total[$__rate_interval])",
     "legendFormat": "{{libp2p_kad_dht_inbound_rpc_requests_total}}"
    },
    {
     "expr": "rate(libp2p_kad_dht_inbound_rpc_errors_total[$__rate_interval])",
     "legendFormat": "{{libp2p_kad_dht_inbound_rpc_errors_total}} (error)"
    }
   ]
  },
  { "title": "Circuit Relay Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Reservations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "libp2p_circuit_relay_server_reservations_total",
     "legendFormat": "reservations"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Active resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    { "expr": "nodejs_active_resources", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nodejs_memory_usage_bytes", "legendFormat": "{{memory}}" }
   ]
  },
  {
   "title": "Active handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    { "expr": "nodejs_active_handles", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count[$__interval])",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}