global:
  scrape_interval: 5s  # How frequently to scrape targets by default.
  evaluation_interval: 15s  # How frequently to evaluate rules.

scrape_configs:
  - job_name: 'js-libp2p-amino-dht-bootstrapper'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8888']

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]

- job_name: 'cadvisor'
  scrape_interval: 15s
  static_configs:
    - targets: ['cadvisor:8080']

- job_name: 'node-exporter'
  scrape_interval: 15s
  static_configs:
    - targets: ['node-exporter:9100']

rule_files:
  - "rules/*.yml"  # This line tells Prometheus where to find the rule files.
